### ISSUE TITLE
Libc Version

### ISSUE THREAD

**Issue by naveenselvan** [ChaO-0/WriteUps#1]
In TAMUctf pwn4 writeup you haven't mentioned the way to find to libc version which was in the remote server. 

Can You Brief how you got the version detail as 'libc6_2.23-0ubuntu3_i386?so'

**Comment by ChaO-0** [comment]
Sorry for the late response. We did mention it in the screenshot of the code. We leak the remote libc by using the **got** address. The **got** address contains the libc address of that **got** function. U will get some hex, everytime u run the payload and it will always change because of **ASLR**. But the last 3 digits wont change, we used that last 3 digits to leak libc in https://libc.blukat.me. BTW, instead of ret2libc, pwn4 has other vulnerability that can easily spawn shell just by using command injection like **';sh'**

**Comment by ChaO-0** [comment]
Oh yea, to leak the libc remotely in 32 bit we always use this payload's skeleton **padding + print/puts@plt + next address+ any@got**

**Comment by naveenselvan** [comment]
All you write are awesome!! I have only one doubt! BTW I still don't understand how you specifically chose this one 'libc6_2.23-0ubuntu3_i386.so' as a shared library which was in the remote server. May I know just with 3 lower byte hex can we know its libc version?

**Comment by ChaO-0** [comment]
I got **'libc6_2.23-0ubuntu3_i386.so'** just by leaking the last 3 digits of the hex from https://libc.blukat.me, all i did is leak the libc in **gets@got**. As you can see, the last 3 digits wont change so we could leak it from https://libc.blukat.me just like this , you see there is only 1 libc version so i decide to use that version of libc :D
![libc](https://user-images.githubusercontent.com/37824174/54749602-05159900-4c10-11e9-893a-7b21484a3b6f.jpg)

**Comment by naveenselvan** [comment]
Thank You So Much!! : )

**Comment by ChaO-0** [comment]
You're welcome ! feel free to ask me more :D

**Comment by NaveenEzio** [comment]
I read you all you writeup's.Some exploits were very differently solved comparing to other's write-up. Its Nice. Keep Hacking :) & Stay Awesome!!.  If you have twitter or any other social site to DM drop your id here.

**Comment by ChaO-0** [comment]
Of course! Thanks for the motivation, come follow me on instagram : @christopheryu_ :D, i'll keep sharing my scripts on my story
